import type { User } from "@/types/auth"
import type { Contact } from "@/types/contacts"
import type { Lead } from "@/types/leads"
import type { Opportunity } from "@/types/opportunities"
import type { Task } from "@/types/tasks"

// Mock Users with different roles
export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    email: "admin@company.com",
    firstName: "John",
    lastName: "Admin",
    role: "Admin",
    permissions: [
      "contacts:read",
      "contacts:create",
      "contacts:update",
      "contacts:delete",
      "leads:read",
      "leads:create",
      "leads:update",
      "leads:delete",
      "opportunities:read",
      "opportunities:create",
      "opportunities:update",
      "opportunities:delete",
      "tasks:read",
      "tasks:create",
      "tasks:update",
      "tasks:delete",
      "reports:read",
    ],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-11-24T10:00:00Z",
  },
  {
    id: "2",
    username: "manager",
    email: "manager@company.com",
    firstName: "Sarah",
    lastName: "Manager",
    role: "Manager",
    permissions: [
      "contacts:read",
      "contacts:create",
      "contacts:update",
      "leads:read",
      "leads:create",
      "leads:update",
      "opportunities:read",
      "opportunities:create",
      "opportunities:update",
      "tasks:read",
      "tasks:create",
      "tasks:update",
      "reports:read",
    ],
    isActive: true,
    createdAt: "2024-01-15T00:00:00Z",
    lastLogin: "2024-11-24T09:30:00Z",
  },
  {
    id: "3",
    username: "sales",
    email: "sales@company.com",
    firstName: "Mike",
    lastName: "Sales",
    role: "Sales Representative",
    permissions: [
      "contacts:read",
      "contacts:create",
      "leads:read",
      "leads:create",
      "leads:update",
      "opportunities:read",
      "opportunities:create",
      "opportunities:update",
      "tasks:read",
      "tasks:create",
      "tasks:update",
    ],
    isActive: true,
    createdAt: "2024-02-01T00:00:00Z",
    lastLogin: "2024-11-24T08:45:00Z",
  },
]

// Mock Contacts
export const mockContacts: Contact[] = [
  {
    id: "c1",
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@techcorp.com",
    phone: "+1-555-0101",
    company: "TechCorp Solutions",
    position: "CTO",
    status: "Active",
    source: "Website",
    tags: ["Enterprise", "Decision Maker"],
    notes: "Interested in enterprise solutions. Follow up next week.",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: "2024-11-20T14:30:00Z",
    assignedTo: "1",
  },
  {
    id: "c2",
    firstName: "David",
    lastName: "Smith",
    email: "david.smith@innovate.io",
    phone: "+1-555-0102",
    company: "Innovate Labs",
    position: "Product Manager",
    status: "Active",
    source: "Referral",
    tags: ["Mid-Market", "Hot Lead"],
    notes: "Referred by existing client. Very interested in our product.",
    createdAt: "2024-10-15T11:00:00Z",
    updatedAt: "2024-11-22T09:15:00Z",
    assignedTo: "2",
  },
  {
    id: "c3",
    firstName: "Lisa",
    lastName: "Chen",
    email: "lisa.chen@startup.com",
    phone: "+1-555-0103",
    company: "Startup Inc",
    position: "Founder & CEO",
    status: "Active",
    source: "Conference",
    tags: ["Startup", "Growing"],
    notes: "Met at Tech Summit 2024. Looking to scale operations.",
    createdAt: "2024-09-20T13:00:00Z",
    updatedAt: "2024-11-18T16:45:00Z",
    assignedTo: "3",
  },
  {
    id: "c4",
    firstName: "Robert",
    lastName: "Williams",
    email: "r.williams@megacorp.com",
    phone: "+1-555-0104",
    company: "MegaCorp International",
    position: "VP of Operations",
    status: "Active",
    source: "LinkedIn",
    tags: ["Enterprise", "Long Sales Cycle"],
    notes: "Large enterprise deal. Multiple stakeholders involved.",
    createdAt: "2024-08-10T09:00:00Z",
    updatedAt: "2024-11-23T11:20:00Z",
    assignedTo: "1",
  },
  {
    id: "c5",
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "j.martinez@boutique.co",
    phone: "+1-555-0105",
    company: "Boutique Consulting",
    position: "Managing Partner",
    status: "Inactive",
    source: "Cold Call",
    tags: ["SMB"],
    notes: "Not interested at this time. Revisit in Q2 2025.",
    createdAt: "2024-07-05T15:00:00Z",
    updatedAt: "2024-10-10T10:00:00Z",
    assignedTo: "2",
  },
]

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: "l1",
    name: "Alex Thompson",
    email: "alex.t@enterprise.com",
    phone: "+1-555-0201",
    company: "Enterprise Systems Ltd",
    status: "Qualified",
    source: "Website Form",
    score: 85,
    estimatedValue: 75000,
    expectedCloseDate: "2024-12-15",
    assignedTo: "1",
    notes: "High-value lead. Requested demo for next week.",
    createdAt: "2024-11-15T10:30:00Z",
    updatedAt: "2024-11-23T14:00:00Z",
  },
  {
    id: "l2",
    name: "Maria Garcia",
    email: "maria.g@growth.io",
    phone: "+1-555-0202",
    company: "Growth Ventures",
    status: "Contacted",
    source: "LinkedIn Ads",
    score: 72,
    estimatedValue: 45000,
    expectedCloseDate: "2025-01-20",
    assignedTo: "2",
    notes: "Interested in starter package. Scheduled call for tomorrow.",
    createdAt: "2024-11-18T14:00:00Z",
    updatedAt: "2024-11-22T16:30:00Z",
  },
  {
    id: "l3",
    name: "James Wilson",
    email: "james.w@digital.com",
    phone: "+1-555-0203",
    company: "Digital Marketing Pro",
    status: "New",
    source: "Google Ads",
    score: 55,
    estimatedValue: 30000,
    expectedCloseDate: "2025-02-01",
    assignedTo: "3",
    notes: "New inbound lead. Need to qualify.",
    createdAt: "2024-11-22T09:00:00Z",
    updatedAt: "2024-11-22T09:00:00Z",
  },
  {
    id: "l4",
    name: "Sophia Lee",
    email: "sophia.l@techstart.com",
    phone: "+1-555-0204",
    company: "TechStart Solutions",
    status: "Converted",
    source: "Referral",
    score: 95,
    estimatedValue: 120000,
    expectedCloseDate: "2024-11-30",
    assignedTo: "1",
    notes: "Converted to opportunity. Excellent fit for our enterprise plan.",
    createdAt: "2024-10-10T11:00:00Z",
    updatedAt: "2024-11-20T13:45:00Z",
  },
  {
    id: "l5",
    name: "Kevin Brown",
    email: "kevin.b@oldschool.com",
    phone: "+1-555-0205",
    company: "Old School Industries",
    status: "Lost",
    source: "Cold Call",
    score: 25,
    notes: "Not a good fit. Budget constraints and timeline mismatch.",
    createdAt: "2024-09-05T15:00:00Z",
    updatedAt: "2024-10-15T10:30:00Z",
    assignedTo: "3",
  },
]

// Mock Opportunities
export const mockOpportunities: Opportunity[] = [
  {
    id: "o1",
    name: "Enterprise Platform Implementation",
    accountName: "TechCorp Solutions",
    stage: "Proposal",
    amount: 250000,
    probability: 75,
    expectedCloseDate: "2024-12-31",
    contactId: "c1",
    assignedTo: "1",
    notes: "Proposal submitted. Waiting for board approval.",
    createdAt: "2024-10-20T10:00:00Z",
    updatedAt: "2024-11-23T15:00:00Z",
  },
  {
    id: "o2",
    name: "Mid-Market Solution",
    accountName: "Innovate Labs",
    stage: "Negotiation",
    amount: 85000,
    probability: 80,
    expectedCloseDate: "2024-12-15",
    contactId: "c2",
    assignedTo: "2",
    notes: "In final negotiations. Pricing discussion ongoing.",
    createdAt: "2024-11-01T11:00:00Z",
    updatedAt: "2024-11-22T14:30:00Z",
  },
  {
    id: "o3",
    name: "Startup Growth Package",
    accountName: "Startup Inc",
    stage: "Qualification",
    amount: 35000,
    probability: 60,
    expectedCloseDate: "2025-01-15",
    contactId: "c3",
    assignedTo: "3",
    notes: "Qualifying their needs and budget. Good engagement so far.",
    createdAt: "2024-11-10T13:00:00Z",
    updatedAt: "2024-11-21T09:00:00Z",
  },
  {
    id: "o4",
    name: "Global Enterprise Deal",
    accountName: "MegaCorp International",
    stage: "Prospecting",
    amount: 500000,
    probability: 30,
    expectedCloseDate: "2025-03-31",
    contactId: "c4",
    assignedTo: "1",
    notes: "Early stage. Multiple meetings scheduled with stakeholders.",
    createdAt: "2024-11-05T09:00:00Z",
    updatedAt: "2024-11-20T16:00:00Z",
  },
  {
    id: "o5",
    name: "Quick Win Deal",
    accountName: "FastTrack Co",
    stage: "Closed Won",
    amount: 25000,
    probability: 100,
    expectedCloseDate: "2024-11-15",
    assignedTo: "2",
    notes: "Deal closed! Contract signed and payment received.",
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: "2024-11-15T14:00:00Z",
  },
  {
    id: "o6",
    name: "Lost to Competitor",
    accountName: "Boutique Consulting",
    stage: "Closed Lost",
    amount: 40000,
    probability: 0,
    expectedCloseDate: "2024-11-01",
    contactId: "c5",
    assignedTo: "2",
    notes: "Lost to competitor. Price was main factor.",
    createdAt: "2024-09-01T11:00:00Z",
    updatedAt: "2024-11-01T10:00:00Z",
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Follow up with Emily Johnson",
    description: "Discuss enterprise platform requirements and schedule technical demo",
    priority: "High",
    status: "Todo",
    dueDate: "2024-11-26",
    assignedTo: "1",
    relatedTo: {
      type: "Contact",
      id: "c1",
      name: "Emily Johnson",
    },
    createdAt: "2024-11-23T10:00:00Z",
    updatedAt: "2024-11-23T10:00:00Z",
  },
  {
    id: "t2",
    title: "Send proposal to Innovate Labs",
    description: "Finalize pricing and send updated proposal document",
    priority: "Urgent",
    status: "In Progress",
    dueDate: "2024-11-25",
    assignedTo: "2",
    relatedTo: {
      type: "Opportunity",
      id: "o2",
      name: "Mid-Market Solution",
    },
    createdAt: "2024-11-22T14:00:00Z",
    updatedAt: "2024-11-23T09:00:00Z",
  },
  {
    id: "t3",
    title: "Qualify new lead - James Wilson",
    description: "Discovery call to understand requirements and budget",
    priority: "Medium",
    status: "Todo",
    dueDate: "2024-11-27",
    assignedTo: "3",
    relatedTo: {
      type: "Lead",
      id: "l3",
      name: "James Wilson",
    },
    createdAt: "2024-11-22T15:00:00Z",
    updatedAt: "2024-11-22T15:00:00Z",
  },
  {
    id: "t4",
    title: "Prepare Q4 sales report",
    description: "Compile quarterly metrics and prepare presentation for leadership",
    priority: "High",
    status: "In Progress",
    dueDate: "2024-11-30",
    assignedTo: "1",
    createdAt: "2024-11-20T11:00:00Z",
    updatedAt: "2024-11-23T13:00:00Z",
  },
  {
    id: "t5",
    title: "Contract signed - FastTrack Co",
    description: "Processed contract and initiated onboarding workflow",
    priority: "Medium",
    status: "Completed",
    dueDate: "2024-11-15",
    assignedTo: "2",
    relatedTo: {
      type: "Opportunity",
      id: "o5",
      name: "Quick Win Deal",
    },
    createdAt: "2024-11-10T10:00:00Z",
    updatedAt: "2024-11-15T16:00:00Z",
  },
  {
    id: "t6",
    title: "Schedule demo for Alex Thompson",
    description: "High-value lead requested product demonstration",
    priority: "High",
    status: "Todo",
    dueDate: "2024-11-28",
    assignedTo: "1",
    relatedTo: {
      type: "Lead",
      id: "l1",
      name: "Alex Thompson",
    },
    createdAt: "2024-11-23T11:00:00Z",
    updatedAt: "2024-11-23T11:00:00Z",
  },
]

// Mock Activities for Dashboard
export interface Activity {
  id: string
  type: "contact" | "lead" | "opportunity" | "task"
  action: string
  description: string
  timestamp: string
  user: string
}

export const mockActivities: Activity[] = [
  {
    id: "a1",
    type: "opportunity",
    action: "Stage Changed",
    description: "Mid-Market Solution moved to Negotiation",
    timestamp: "2024-11-23T14:30:00Z",
    user: "Sarah Manager",
  },
  {
    id: "a2",
    type: "task",
    action: "Completed",
    description: "Contract signed - FastTrack Co marked as completed",
    timestamp: "2024-11-23T13:00:00Z",
    user: "Sarah Manager",
  },
  {
    id: "a3",
    type: "lead",
    action: "Created",
    description: "New lead: James Wilson from Google Ads",
    timestamp: "2024-11-22T09:00:00Z",
    user: "Mike Sales",
  },
  {
    id: "a4",
    type: "contact",
    action: "Updated",
    description: "Emily Johnson contact information updated",
    timestamp: "2024-11-20T14:30:00Z",
    user: "John Admin",
  },
  {
    id: "a5",
    type: "opportunity",
    action: "Created",
    description: "New opportunity: Startup Growth Package",
    timestamp: "2024-11-10T13:00:00Z",
    user: "Mike Sales",
  },
]

// Mock Dashboard Stats
export interface DashboardStats {
  totalRevenue: number
  revenueChange: number
  activeOpportunities: number
  opportunitiesChange: number
  conversionRate: number
  conversionChange: number
  avgDealSize: number
  dealSizeChange: number
}

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 895000,
  revenueChange: 12.5,
  activeOpportunities: 4,
  opportunitiesChange: -8.2,
  conversionRate: 34.2,
  conversionChange: 5.7,
  avgDealSize: 133500,
  dealSizeChange: 18.3,
}

// Helper function to simulate API delay
export const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

// Mock credentials for login
export const MOCK_CREDENTIALS = {
  admin: { username: "admin", password: "admin123" },
  manager: { username: "manager", password: "manager123" },
  sales: { username: "sales", password: "sales123" },
}
